---

- name: "blacklistd: Stop play if blacklistd is enabled and no service exists"
  block:
    - stat:
        path: "/etc/rc.d/blacklistd"
      register: pf_blacklistd_service
    - debug:
        msg: "Play stopped. blacklistd is enabled and no service exists."
      when:
        - pf_blacklistd_enable
        - not pf_blacklistd_service.stat.exists
    - meta: end_play
      when:
        - pf_blacklistd_enable
        - not pf_blacklistd_service.stat.exists

- name: "blacklistd: Configure /etc/blacklistd.conf"
  template:
    dest: "/etc/blacklistd.conf"
    src: "blacklistd.conf.j2"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "{{ pf_backup_conf }}"
  notify: restart blacklistd

# EOF
...
