---

- name: "blacklistdconf: Configure /etc/blacklistd.conf"
  template:
    dest: "/etc/blacklistd.conf"
    src: "blacklistd.conf.j2"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: yes
  notify: restart blacklistd

# EOF
...
