---

# Configure /etc/pf.conf without notification to reload pf
- name: Configure rules using {{ pf_type }}-pf.conf.j2 template
  template: >
    dest="/etc/pf.conf"
    src="{{ pf_type }}-pf.conf.j2"
    owner="root"
    group="wheel"
    mode="0640"
    backup="yes"
  tags: config_pf_rules_no_notification

# EOF
...
