---
# tasks for freebsd-pf

- import_tasks: debug.yml
  when: pf_debug|bool
  tags: [pf_debug, always]

- import_tasks: packages.yml
  tags: pf_packages

- import_tasks: sshguard.yml
  tags: pf_sshguard

- import_tasks: blacklistd.yml
  tags: pf_blacklistd

- import_tasks: fail2ban.yml
  tags: pf_fail2ban

- import_tasks: pfconf.yml
  tags: pf_conf

- import_tasks: rcconf-sshguard.yml
  tags: pf_rcconf_sshguard

- import_tasks: rcconf-blacklistd.yml
  tags: pf_rcconf_blacklistd

- import_tasks: rcconf-fail2ban.yml
  tags: pf_rcconf_fail2ban

- import_tasks: rcconf-pf.yml
  tags: pf_rcconf_pf

- import_tasks: rcconf-pflog.yml
  tags: pf_rcconf_pflog

# EOF
...
