---

- name: "packages: Install sshguard packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ pf_sshguard_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - pf_sshguard_enable
    - freebsd_install_method == "packages"

- name: "packages: Install sshguard ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ pf_sshguard_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - pf_sshguard_enable
    - freebsd_install_method == "ports"

- name: "packages: Install fail2ban packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ pf_fail2ban_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - pf_fail2ban_enable
    - freebsd_install_method == "packages"

- name: "packages: Install fail2ban ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ pf_fail2ban_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - pf_fail2ban_enable
    - freebsd_install_method == "ports"

# EOF
...
