---

- name: "pfconf: Debug"
  vars:
    msg: |-
         pf_type [{{ pf_type }}]
         pf_ext_if [{{ pf_ext_if }}]
         pfconf_validate [{{ pfconf_validate }}]
         pfconf_only [{{ pfconf_only }}]
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
  when: pf_debug|bool

- name: "pfconf: Configure and validate rules using {{ pf_type }}-pf.conf.j2 template"
  block:
    - name: "pfconf: Configure rules using {{ pf_type }}-pf.conf.j2 template"
      ansible.builtin.template:
        dest: /etc/pf.conf
        src: "{{ pf_type }}-pf.conf.j2"
        owner: root
        group: wheel
        mode: "0640"
        backup: "{{ pf_backup_conf }}"
        validate: "{{ pfconf_validate_command }}"
      notify: reload pf
  rescue:
    - name: "pfconf: Validation failed"
      ansible.builtin.fail:
        msg: "Validation error: {{ ansible_failed_result }}"
  when: pfconf_validate|bool

- name: "pfconf: Configure, do not validate rules using {{ pf_type }}-pf.conf.j2 template"
  block:
    - name: "Fail when pfconf_validate=False and pfconf_only=False"
      ansible.builtin.fail:
        msg: "Failed. Validation can be turned off if pfconf_only=True."
      when: not pfconf_only|bool
    - name: "pfconf: Configure, do not validate rules using {{ pf_type }}-pf.conf.j2 template"
      ansible.builtin.template:
        dest: /etc/pf.conf
        src: "{{ pf_type }}-pf.conf.j2"
        owner: root
        group: wheel
        mode: "0640"
        backup: "{{ pf_backup_conf }}"
  when: not pfconf_validate|bool

# EOF
...
