---

- name: "pfconf: Debug"
  debug:
    msg: "pf_ext_if: {{ pf_ext_if }}"
  when: pf_debug|bool

- name: "pfconf: Configure rules using {{ pf_type }}-pf.conf.j2 template"
  when: pfconf_validate|bool
  block:
    - name: "pfconf: Configure rules using {{ pf_type }}-pf.conf.j2 template"
      template:
        dest: "/etc/pf.conf"
        src: "{{ pf_type }}-pf.conf.j2"
        owner: "root"
        group: "wheel"
        mode: "0640"
        backup: "{{ pf_backup_conf }}"
        validate: "{{ pfconf_validate_command }}"
      notify: reload pf
  rescue:
    - name: "pfconf: Validation failed "
      fail:
        msg: "Validation error: {{ ansible_failed_result }}"

- name: "pfconf: Configure rules using {{ pf_type }}-pf.conf.j2 template"
  when: not pfconf_validate|bool
  block:
    - name: "Fail when pfconf_validate=no and pfconf_only=no"
      fail:
        msg: "Validation can be turned off. Only if pfconf_only=yes. End of play."
      when: not pfconf_only
    - name: "pfconf: Configure rules using {{ pf_type }}-pf.conf.j2 template"
      template:
        dest: "/etc/pf.conf"
        src: "{{ pf_type }}-pf.conf.j2"
        owner: "root"
        group: "wheel"
        mode: "0640"
        backup: "{{ pf_backup_conf }}"

# EOF
...
