---

# pflog
- name: "rcconf: Enable and start pflog"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^pflog_enable"
    line: "pflog_enable=\"YES\""
    backup: "{{ pf_backup_conf }}"
  notify: enable and start pflog
  when: pflog_enable
  
- name: "rcconf: Disable and stop pflog"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^pflog_enable"
    line: "pflog_enable=\"NO\""
    backup: "{{ pf_backup_conf }}"
  notify: disable and stop pflog
  when: not pflog_enable

- name: "rcconf: Configure pflog"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.line }}"
    backup: "{{ pf_backup_conf }}"
  loop:
    - { regexp: "pflog_logfile", line: "\"{{ pflog_logfile }}\""}
    - { regexp: "pflog_flags", line: "\"{{ pflog_flags }}\""}
  notify: reload pflog

# EOF
...
