---

- name: "sshguard: Stat /usr/local/etc/rc.d/sshguard"
  stat:
    path: "/usr/local/etc/rc.d/sshguard"
  register: pf_sshguard_service

- name: "sshguard: Stop play if sshguard is enabled and no service exists"
  block:
    - debug:
        msg: "Play stopped. sshguard is enabled, but no service exists."
      when:
        - pf_sshguard_enable
        - not pf_sshguard_service.stat.exists
    - meta: end_play
      when:
        - pf_sshguard_enable
        - not pf_sshguard_service.stat.exists
  when: not ansible_check_mode

- name: "sshguard: Configure pf whitelist sshguard"
  lineinfile:
    dest: "/usr/local/etc/sshguard.whitelist"
    line: "{{ item }}"
    backup: "{{ pf_backup_conf }}"
  loop: "{{ pf_ssh_whitelist }}"
  when: pf_sshguard_enable
  notify: restart sshguard

# EOF
...
