---
# handlers for freebsd-pf

# blacklistd ---------------------------------------------------------

- name: enable and start blacklistd
  service:
    name: "blacklistd"
    state: started
    enabled: yes
  when:
    - pf_blacklistd_enable
    - pf_blacklistd_service.stat.exists

- name: disable and stop blacklistd
  service:
    name: "blacklistd"
    state: stopped
    enabled: no
  when:
    - not pf_blacklistd_enable
    - pf_blacklistd_service.stat.exists

- name: restart blacklistd
  service:
    name: "blacklistd"
    state: restarted
  when:
    - pf_blacklistd_enable
    - pf_blacklistd_service.stat.exists

# /etc/rc.d/blacklistd: unknown directive 'reload'.
#  - name: reload blacklistd
#    service:
#      name: "blacklistd"
#      state: reloaded

# EOF
...
