---
# handlers for freebsd_pf

- name: Enable and start sshguard
  listen: enable and start sshguard
  ansible.builtin.service:
    name: sshguard
    state: started
    enabled: true
  when: pf_sshguard_enable | bool

- name: Disable and stop sshguard
  listen: disable and stop sshguard
  ansible.builtin.service:
    name: sshguard
    state: stopped
    enabled: false
  when: not pf_sshguard_enable | bool

- name: Restart sshguard
  listen: restart sshguard
  ansible.builtin.service:
    name: sshguard
    state: restarted
  when: pf_sshguard_enable | bool

#  /usr/local/etc/rc.d/sshguard: unknown directive 'reload'.
# - name: reload sshguard
#   service:
#     name: "sshguard"
#     state: reloaded

# EOF
